import { z } from 'zod';

/** cuid-style ids generated by Prisma. Kept loose on purpose, but bounded. */
export const IdSchema = z.string().regex(/^[a-z0-9]{20,32}$/, 'invalid id');

export const PaginationQuerySchema = z.object({
  cursor: IdSchema.optional(),
  limit: z.coerce.number().int().min(1).max(200).default(50),
});
export type PaginationQuery = z.infer<typeof PaginationQuerySchema>;

export interface Page<T> {
  items: T[];
  nextCursor: string | null;
}

export interface ApiErrorBody {
  error: { code: string; message: string; details?: unknown };
}
